name: Run & Release

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 1' 
  workflow_dispatch:

permissions:
  contents: write   

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true  

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Update references
      - name: Git Submodule Update
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive


      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build APKG
        run: python app.py

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"


      - name: Create Release
        run: |
          gh release create \
            ${{ format('${{ steps.date.outputs.date }}', github.run_id) }} \
            toki-pona-deck.apkg \
            --title "Release ${{ format('${{ steps.date.outputs.date }}', github.run_id) }}" \
            --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}